version: "3"

services:

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

  real_device:
    image: appium/appium
    depends_on:
      - selenium-hub
    network_mode: "service:selenium-hub"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium-hub

  samsung_galaxy:
    image: budtmo/docker-android-x86-8.1
    container_name: samsung_galaxy
    privileged: true
    # Increase scale number if needed
    scale: 1
    depends_on:
      - selenium-hub
      - real_device
    ports:
      - "6080:6080"
    volumes:
      - ./video-samsung:/tmp/video
      - $PWD/sample_apps:/root/tmp
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium-hub
      - MOBILE_WEB_TEST=false
      - AUTO_RECORD=true

  tests:
    build:
      context: ./src_code
      dockerfile: Dockerfile
    container_name: tests
    tty: true